{{- if not .Values.caches.existingPvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "metranova-flow-pipeline.fullname" . }}-caches
  labels:
    {{- include "metranova-flow-pipeline.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.caches.storageClassName }}
  storageClassName: {{ .Values.caches.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.caches.storageSize }}
{{- end }}
