{{- if not .Values.caches.existingPvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "metranova-snmp-pipeline.fullname" . }}-caches
  labels:
    {{- include "metranova-snmp-pipeline.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.caches.storageClassName }}
  storageClassName: {{ .Values.caches.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.caches.storageSize }}
{{- end }}
---
{{- if and .Values.redis.enabled .Values.redis.persistence.enabled (not .Values.redis.persistence.existingPvc) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "metranova-snmp-pipeline.fullname" . }}-redis-data
  labels:
    {{- include "metranova-snmp-pipeline.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.redis.persistence.storageClassName }}
  storageClassName: {{ .Values.redis.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.storageSize }}
{{- end }}
